### ISSUE TITLE
Json操作目录中，文件名是json.py,文件中import json 这么写会找不到自带的python吧

### ISSUE THREAD

**Issue by jianlong-sun** [gxcuizy/Python#9]
初学python 如果说的不对 请见谅

**Comment by renhaiwen2018** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by nightzjp** [comment]
不建议文件名跟内置模块名称相同。

**Comment by renhaiwen2018** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by gxcuizy** [comment]
是的，不能和内置模块名称重名，import会失败，我是示例的，为了能快速识别到看文件就知道这个是什么demo，所以才重名的，实际应用中不能这么命名的
